<a href="https://colab.research.google.com/github/Deeksha-Pandit/EVA4-S14/blob/master/Final/Mean_STD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:

from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:

import zipfile

archive = zipfile.ZipFile('/content/gdrive/My Drive/Mask_Rcnn/Dataset/data_part1.zip')

for file in archive.namelist():
    if file.startswith('data_1/Depth/'):
        archive.extract(file, '/content/')

In [0]:

import zipfile

archive = zipfile.ZipFile('/content/gdrive/My Drive/Mask_Rcnn/Dataset/data_part2.zip')

for file in archive.namelist():
    if file.startswith('data_2/Depth/'):
        archive.extract(file, '/content/')

In [0]:

import zipfile

archive = zipfile.ZipFile('/content/gdrive/My Drive/Mask_Rcnn/Dataset/data_part3.zip')

for file in archive.namelist():
    if file.startswith('data_3/Depth/'):
        archive.extract(file, '/content/')

In [0]:

import zipfile

archive = zipfile.ZipFile('/content/gdrive/My Drive/Mask_Rcnn/Dataset/data_part4.zip')

for file in archive.namelist():
    if file.startswith('data_4/Depth/'):
        archive.extract(file, '/content/')

In [0]:
import zipfile

archive = zipfile.ZipFile('/content/gdrive/My Drive/Mask_Rcnn/Dataset/data_part5.zip')

for file in archive.namelist():
    if file.startswith('data_5/Depth/'):
        archive.extract(file, '/content/')

In [0]:

from tqdm import notebook
from PIL import Image
import numpy as np
n = 0
s = np.zeros(3)
sq = np.zeros(3)

for i in notebook.tqdm(range(80000)):
    
      img = Image.open(f'/content/data_1/Depth/depth{str(i+1)}.jpg')
      x = np.array(img)/255
      s += x.sum(axis=(0,1))
      sq += np.sum(np.square(x), axis=(0,1))
      n += x.shape[0]*x.shape[1]

for i in notebook.tqdm(range(80000,160000)):
    
      img = Image.open(f'/content/data_2/Depth/depth{str(i+1)}.jpg')
      x = np.array(img)/255
      s += x.sum(axis=(0,1))
      sq += np.sum(np.square(x), axis=(0,1))
      n += x.shape[0]*x.shape[1]

for i in notebook.tqdm(range(160000,240000)):
    
      img = Image.open(f'/content/data_3/Depth/depth{str(i+1)}.jpg')
      x = np.array(img)/255
      s += x.sum(axis=(0,1))
      sq += np.sum(np.square(x), axis=(0,1))
      n += x.shape[0]*x.shape[1]

for i in notebook.tqdm(range(240000,320000)):
    
      img = Image.open(f'/content/data_4/Depth/depth{str(i+1)}.jpg')
      x = np.array(img)/255
      s += x.sum(axis=(0,1))
      sq += np.sum(np.square(x), axis=(0,1))
      n += x.shape[0]*x.shape[1]

for i in notebook.tqdm(range(320000,400000)):
    
      img = Image.open(f'/content/data_5/Depth/depth{str(i+1)}.jpg')
      x = np.array(img)/255
      s += x.sum(axis=(0,1))
      sq += np.sum(np.square(x), axis=(0,1))
      n += x.shape[0]*x.shape[1]

mean = s/n
std = np.sqrt((sq/n - np.square(mean)))
print(mean, sq/n, std, n)


[0.50911522 0.50911522 0.50911522] [0.33857744 0.33857744 0.33857744] [0.28174302 0.28174302 0.28174302] 20070400000


In [0]:
n

20070400000

In [0]:
mean

array([0.50911522, 0.50911522, 0.50911522])

In [0]:
std

array([0.28174302, 0.28174302, 0.28174302])